version: 2

jobs:
  serverapp:
    docker:
      - image: circleci/node:7
    steps:
      - run: git clone https://github.com/franczak/CsGoBuffServer.git
      - run: ls
      - run: npm install
      - run: npm start
  frontapp:
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: npm install
      - run: npm start
      - run: npm run cypress:run
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - serverapp
      - frontapp:
          requires:
            - serverapp