version: 2

jobs:
  build:
    docker:
      - image: cypress/base
    steps:
      - run:
        command: |
          git clone https://github.com/franczak/CsGoBuffServer.git
          cd CsGoBuffServer/
          npm install
      - run:
        command: |
          cd CsGoBuffServer/
          npm start
        background: true
      - run:
        command: |
          checkout
          npm install
      - run:
        command: npm start
        background: true
      - run: npm run cypress:run