version: 2

jobs:
  build:
    docker:
      - image: cypress/base
    steps:
      - run:
          working_directory: ~/
          command: git clone https://github.com/franczak/CsGoBuffServer.git
      - run:
          working_directory: ~/CsGoBuffServer/
          command: npm install
      - run:
          working_directory: ~/CsGoBuffServer/
          command: npm start
          background: true
      - checkout
      - run: npm install
      - run:
          command: npm start
          background: true
      - run: npm run cypress:run
      - store_artifacts:
          path: cypress/videos