version: 2

jobs:
  server:
    docker:
      - image: circleci/node:7
    steps:
      - run: git clone https://github.com/franczak/CsGoBuffServer.git
      - run: npm install
      - run: npm start
  build:
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: npm install
      - run: npm start
      - run: npm run cypress:run


workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - server
      - build:
          requires:
            - server