version: 2
workflows:
  version: 2
  build_and_test:
    jobs:
      - server
      - build
jobs:
  server:
    docker:
      - image: circleci/node:7
    steps:
      - run: git clone https://github.com/franczak/CsGoBuffServer.git
      - run: npm install
      - run: npm start
  build:
    docker:
      - image: circleci/node:7
    steps:
      - run: git clone https://github.com/franczak/CsGoBuffServer.git
      - run: npm install
      - run: npm start
      - run: npm run cypress:run